### ISSUE TITLE
create web footer

### ISSUE THREAD

**Issue by grindarius** [grindarius/reeba#174]

**Comment by pasinchanla** [comment]
![image](https://user-images.githubusercontent.com/69805712/154274847-cae1aeaa-dea2-45bf-9e0a-786c56aad0ae.png)
Footer ฝั่งซ้ายจะมีแค่ social network ทั่วไปเช่น fb ig
ฝั่งขวาจะเป็นเบอร์กับเมล (ใช้เป็นข้อมูลเฟคได้เลย)

**Comment by grindarius** [comment]
cookie policy ไม่เกี่ยวนะ @PawinaK
