### ISSUE TITLE
probably refactor div nestings

### ISSUE THREAD

**Issue by grindarius** [grindarius/reeba#196]
![GIF 11-02-2022 12-07-18](https://user-images.githubusercontent.com/60266519/153540442-812d7469-50db-4f24-9c74-78f7fc664d5a.gif)

I don't think you need 3 divs to do that kind of table manipulation, it all could be done with 1 div. Refactor it, unless you can explain well enough why you'd need 3 divs to do that kind of job.

**Comment by Baramee0** [comment]
I'll go fix it.
