### ISSUE TITLE
add users settings in profile

### ISSUE THREAD

**Issue by pasinchanla** [grindarius/reeba#205]

**Comment by grindarius** [comment]
same as how codee.club does

**Comment by pasinchanla** [comment]
![image](https://user-images.githubusercontent.com/69805712/161992227-104779b4-396f-4cad-abdc-70ed34355b84.png)
![image](https://user-images.githubusercontent.com/69805712/161992280-4c73ea75-1edc-4671-9695-fb631d92ce1a.png)
