### ISSUE TITLE
rethink how to input tel. number in sign up

### ISSUE THREAD

**Issue by pasinchanla** [grindarius/reeba#220]
ตอนนี้มันยังเป็นช่องให้กรอกอย่างเดียวอยู่เนอะ

ต่อไปที่ต้องคิดคือปกติเวลาพิมพ์เบอร์โทรศัพท์จะมีคน 2 แบบ
1. พิมพ์ 0 ไว้ข้างหน้าด้วย เช่น 095-xxx-xxxx
2. ไม่พิมพ์ 0 เลย เช่น 95-000-0000

คำถามคือเราจะทำยังไงให้เวลาพิมพ์แบบแรกแล้วเว็บเราจะตัด 0 ตัวแรกออก

**Comment by pasinchanla** [comment]
สืบเนื่องจาก #218 ตอนนี้มันยังเป็นช่องให้กรอกอย่างเดียวอยู่เนอะ

ต่อไปที่ต้องคิดคือปกติเวลาพิมพ์เบอร์โทรศัพท์จะมีคน 2 แบบ
1. พิมพ์ 0 ไว้ข้างหน้าด้วย เช่น 095-xxx-xxxx
2. ไม่พิมพ์ 0 เลย เช่น 95-000-0000

คำถามคือเราจะทำยังไงให้เวลาพิมพ์แบบแรกแล้วเว็บเราจะตัด 0 ตัวแรกออก

**Comment by grindarius** [comment]
closed because trunk prefix is too versatile and some countries doesn't start with 0. Pushing this to a user is probably a better point
