### ISSUE TITLE
create followers modal and following modal to display users list

### ISSUE THREAD

**Issue by grindarius** [grindarius/reeba#291]

**Comment by grindarius** [comment]
kinda like instargam follower modal

**Comment by grindarius** [comment]
![image](https://user-images.githubusercontent.com/60266519/160331435-dafc1c82-cb36-49d3-90a9-a9b806d7695c.png)

**Comment by pasinchanla** [comment]
![image](https://user-images.githubusercontent.com/69805712/161984135-f9c3e364-85da-4fef-9383-a1a5f4e9d6dd.png)
เอาแค่นี้พอ
